Feature/details
davidcre/News2020Android pull request #9
Opened 2020-04-10 09:18 UTC by LukaAleksic

2020-04-14 13:39 UTC, davidcre requested changes

2020-04-14 13:39 UTC, davidcre commented on app/src/main/java/com/example/readnews/details/DetailsFragment.kt
> +    private val viewModel: DetailsViewModel by lazy {
C'est top ce by lazy.

2020-04-14 13:39 UTC, davidcre commented on app/src/main/java/com/example/readnews/details/DetailsFragment.kt
> +
Un peu trop de saut de ligne je trouve

2020-04-14 13:39 UTC, davidcre commented on app/src/main/java/com/example/readnews/everything/EverythingFragment.kt
>  class EverythingFragment : Fragment() {
J'aurai appelé ca EveryNews ou AllNews perso, everything c'est un peu vague

2020-04-14 13:39 UTC, davidcre commented on app/src/main/java/com/example/readnews/everything/EverythingFragment.kt
> +                view!!.findNavController()
c'est mieux d'éviter les !! quifotn des crashs au runtime.

Hapintuellement le : 
optionnal?.let { nonNullOptionnal -> ... } est préféré dans une bonne partie des cas.
Comme ca le block n'est éxécuté que si l'optionnal est non null.
Sinon rien n'est executé, mieux qu'un crash du coup :)

2020-04-14 13:39 UTC, davidcre commented on app/src/main/java/com/example/readnews/headlines/TopHeadlinesFragment.kt
> +                view!!.findNavController()
Idem qu'au dessus pour le let.

2020-04-17 08:25 UTC, kotvdev approved these changes

2020-04-17 08:27 UTC, davidcre approved these changes

2020-04-17 09:24 UTC, merged